use super::SymbolTrait;
use crate::Scale;

/// Symbols for area objects
#[allow(missing_docs)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum AreaSymbol {
    BrokenGround,
    VeryBrokenGround,
    GiganticBoulder,
    BoulderField,
    DenseBoulderField,
    StonyGroundSlow,
    StonyGroundWalk,
    StonyGroundFight,
    SandyGround,
    BareRock,
    UncrossableWaterWithBankLine,
    UncrossableWaterWithoutBankLine,
    UncrossableWaterDominantWithBankLine,
    UncrossableWaterDominantWithoutBankLine,
    ShallowWaterWithSolidBankLine,
    ShallowWaterWithDashedBankLine,
    ShallowWaterWithoutBankLine,
    SmallShallowWater,
    UncrossableMarshWithBankLine,
    UncrossableMarshWithoutBankLine,
    Marsh,
    IndistinctMarsh,
    OpenLand,
    OpenLandScatteredTrees,
    OpenLandScatteredBushes,
    RoughOpenLand,
    RoughOpenLandScatteredTrees,
    RoughOpenLandScatteredBushes,
    Forest,
    LightGreen,
    LightGreenOneDirectionWhite,
    UnderGrowth,
    MediumGreen,
    MediumGreenOneDirectionWhite,
    MediumGreenOneDirectionLightGreen,
    DenseUnderGrowth,
    DarkGreen,
    DarkGreenOneDirectionWhite,
    DarkGreenOneDirectionLightGreen,
    DarkGreenOneDirectionMediumGreen,
    CultivatedLand,
    Orchard,
    RoughOrchard,
    Vineyard,
    RoughVineyard,
    PavedAreaWithBoundary,
    PavedAreaWithoutBoundary,
    PrivateArea,
    Building,
    LargeBuildingWithOutline,
    LargeBuildingWithoutOutline,
    CanopyWithOutline,
    CanopyWithoutOutline,
    MagneticNorthBlack,
    MagneticNorthBlue,
    OutOfBounds,
}

impl SymbolTrait for AreaSymbol {
    // in square meters
    fn min_size(&self, scale: Scale) -> f64 {
        const CONVERSION: f64 = 4. / 9.;

        let min = match self {
            AreaSymbol::BrokenGround => 100.,
            AreaSymbol::VeryBrokenGround => 49.,
            AreaSymbol::GiganticBoulder => 67.,
            AreaSymbol::BoulderField => 225.,
            AreaSymbol::DenseBoulderField => 100.,
            AreaSymbol::StonyGroundSlow => 100.,
            AreaSymbol::StonyGroundWalk => 64.,
            AreaSymbol::StonyGroundFight => 49.,
            AreaSymbol::SandyGround => 225.,
            AreaSymbol::BareRock => 225.,
            AreaSymbol::UncrossableWaterWithBankLine => 64.,
            AreaSymbol::UncrossableWaterWithoutBankLine => 64.,
            AreaSymbol::UncrossableWaterDominantWithBankLine => 64.,
            AreaSymbol::UncrossableWaterDominantWithoutBankLine => 64.,
            AreaSymbol::ShallowWaterWithSolidBankLine => 110.25,
            AreaSymbol::ShallowWaterWithDashedBankLine => 110.25,
            AreaSymbol::ShallowWaterWithoutBankLine => 110.25,
            AreaSymbol::SmallShallowWater => 64.,
            AreaSymbol::UncrossableMarshWithBankLine => 110.25,
            AreaSymbol::UncrossableMarshWithoutBankLine => 110.25,
            AreaSymbol::Marsh => 45.,
            AreaSymbol::IndistinctMarsh => 315.,
            AreaSymbol::OpenLand => 64.,
            AreaSymbol::OpenLandScatteredTrees => 900.,
            AreaSymbol::OpenLandScatteredBushes => 900.,
            AreaSymbol::RoughOpenLand => 225.,
            AreaSymbol::RoughOpenLandScatteredTrees => 1406.25,
            AreaSymbol::RoughOpenLandScatteredBushes => 1406.25,
            AreaSymbol::LightGreen => 225.,
            AreaSymbol::LightGreenOneDirectionWhite => 225.,
            AreaSymbol::UnderGrowth => 337.5,
            AreaSymbol::MediumGreen => 110.25,
            AreaSymbol::MediumGreenOneDirectionWhite => 110.25,
            AreaSymbol::MediumGreenOneDirectionLightGreen => 110.25,
            AreaSymbol::DenseUnderGrowth => 225.,
            AreaSymbol::DarkGreen => 64.,
            AreaSymbol::DarkGreenOneDirectionWhite => 64.,
            AreaSymbol::DarkGreenOneDirectionLightGreen => 64.,
            AreaSymbol::DarkGreenOneDirectionMediumGreen => 64.,
            AreaSymbol::CultivatedLand => 2025.,
            AreaSymbol::Orchard => 900.,
            AreaSymbol::RoughOrchard => 900.,
            AreaSymbol::Vineyard => 900.,
            AreaSymbol::RoughVineyard => 900.,
            AreaSymbol::PavedAreaWithBoundary => 225.,
            AreaSymbol::PavedAreaWithoutBoundary => 225.,
            AreaSymbol::PrivateArea => 225.,
            AreaSymbol::Building => 56.25,
            AreaSymbol::LargeBuildingWithOutline => 5625.,
            AreaSymbol::LargeBuildingWithoutOutline => 5625.,
            AreaSymbol::CanopyWithOutline => 81.,
            AreaSymbol::CanopyWithoutOutline => 81.,
            AreaSymbol::OutOfBounds => 2025.,
            _ => 0.,
        };
        match scale {
            Scale::S10_000 => min * CONVERSION,
            Scale::S15_000 => min,
        }
    }

    fn id(&self) -> u8 {
        match self {
            AreaSymbol::BrokenGround => 21,
            AreaSymbol::VeryBrokenGround => 23,
            AreaSymbol::GiganticBoulder => 38,
            AreaSymbol::BoulderField => 41,
            AreaSymbol::DenseBoulderField => 44,
            AreaSymbol::StonyGroundSlow => 45,
            AreaSymbol::StonyGroundWalk => 47,
            AreaSymbol::StonyGroundFight => 48,
            AreaSymbol::SandyGround => 49,
            AreaSymbol::BareRock => 50,
            AreaSymbol::UncrossableWaterWithBankLine => 52,
            AreaSymbol::UncrossableWaterWithoutBankLine => 53,
            AreaSymbol::UncrossableWaterDominantWithBankLine => 54,
            AreaSymbol::UncrossableWaterDominantWithoutBankLine => 55,
            AreaSymbol::ShallowWaterWithSolidBankLine => 57,
            AreaSymbol::ShallowWaterWithDashedBankLine => 58,
            AreaSymbol::ShallowWaterWithoutBankLine => 59,
            AreaSymbol::SmallShallowWater => 62,
            AreaSymbol::UncrossableMarshWithBankLine => 67,
            AreaSymbol::UncrossableMarshWithoutBankLine => 68,
            AreaSymbol::Marsh => 69,
            AreaSymbol::IndistinctMarsh => 72,
            AreaSymbol::OpenLand => 77,
            AreaSymbol::OpenLandScatteredTrees => 78,
            AreaSymbol::OpenLandScatteredBushes => 79,
            AreaSymbol::RoughOpenLand => 80,
            AreaSymbol::RoughOpenLandScatteredTrees => 81,
            AreaSymbol::RoughOpenLandScatteredBushes => 82,
            AreaSymbol::Forest => 83,
            AreaSymbol::LightGreen => 84,
            AreaSymbol::LightGreenOneDirectionWhite => 85,
            AreaSymbol::UnderGrowth => 86,
            AreaSymbol::MediumGreen => 87,
            AreaSymbol::MediumGreenOneDirectionWhite => 88,
            AreaSymbol::MediumGreenOneDirectionLightGreen => 89,
            AreaSymbol::DenseUnderGrowth => 90,
            AreaSymbol::DarkGreen => 91,
            AreaSymbol::DarkGreenOneDirectionWhite => 92,
            AreaSymbol::DarkGreenOneDirectionLightGreen => 93,
            AreaSymbol::DarkGreenOneDirectionMediumGreen => 94,
            AreaSymbol::CultivatedLand => 96,
            AreaSymbol::Orchard => 97,
            AreaSymbol::RoughOrchard => 98,
            AreaSymbol::Vineyard => 99,
            AreaSymbol::RoughVineyard => 100,
            AreaSymbol::PavedAreaWithBoundary => 107,
            AreaSymbol::PavedAreaWithoutBoundary => 108,
            AreaSymbol::PrivateArea => 139,
            AreaSymbol::Building => 141,
            AreaSymbol::LargeBuildingWithOutline => 143,
            AreaSymbol::LargeBuildingWithoutOutline => 144,
            AreaSymbol::CanopyWithOutline => 146,
            AreaSymbol::CanopyWithoutOutline => 147,
            AreaSymbol::MagneticNorthBlack => 160,
            AreaSymbol::MagneticNorthBlue => 161,
            AreaSymbol::OutOfBounds => 167,
        }
    }

    fn is_rotatable(&self) -> bool {
        matches!(
            self,
            AreaSymbol::DarkGreenOneDirectionMediumGreen
                | AreaSymbol::DarkGreenOneDirectionLightGreen
                | AreaSymbol::DarkGreenOneDirectionWhite
                | AreaSymbol::MediumGreenOneDirectionLightGreen
                | AreaSymbol::MediumGreenOneDirectionWhite
                | AreaSymbol::LightGreenOneDirectionWhite
                | AreaSymbol::RoughVineyard
                | AreaSymbol::Vineyard
        )
    }
}
