use super::SymbolTrait;
use crate::writer::Scale;

/// Symbols for line objects
#[allow(missing_docs)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum LineSymbol {
    Contour,
    BasemapContour,
    NegBasemapContour,
    IndexContour,
    FormLine,
    EarthBank,
    EarthBankTopLine,
    EarthBankTagLine,
    EarthWall,
    RetainingEarthWall,
    RuinedEarthWall,
    ErosionGully,
    SmallErosionGully,
    ImpassableCliff,
    ImpassableCliffTopLine,
    ImpassableCliffTagLine,
    Cliff,
    CliffWithTags,
    Trench,
    BankLine,
    ShallowWaterOutline,
    ShallowWaterDashedOutline,
    CrossableWatercourse,
    SmallCrossableWatercourse,
    SeasonalWatercourse,
    NarrowMarsh,
    Hedge,
    DistinctCultivationBoundary,
    DistinctVegetationBoundary,
    PavedAreaBoundingLine,
    Road,
    RoadDualCarriageway,
    GravelRoad,
    VehicleTrack,
    Footpath,
    SmallFootpath,
    IndistinctFootpath,
    NarrowRide,
    NarrowRideEasyRunning,
    NarrowRideNormalRunning,
    NarrowRideSlowRunning,
    NarrowRideWalk,
    Railway,
    ImpassableRailway,
    SmallPowerLine,
    LargePowerLine,
    MajorPowerLine,
    MajorPowerLineWithPylons,
    BridgeTunnel,
    Wall,
    RetainingWall,
    RuinedWall,
    ImpassableWall,
    Fence,
    RuinedFence,
    ImpassableFence,
    PrivateAreaBoundingLine,
    LargeBuildingOutline,
    CanopyOutline,
    Ruin,
    ProminentLinearFeature,
    ImpassableProminentLinearFeature,
    Stairway,
    SimpleOrienteeringCourse,
}

impl SymbolTrait for LineSymbol {
    // in meters
    fn min_size(&self, scale: Scale) -> f64 {
        const CONVERSION: f64 = 2. / 3.;
        let min = match self {
            LineSymbol::FormLine => 16.5,
            LineSymbol::EarthBank => 9.,
            LineSymbol::EarthBankTopLine => 9.,
            LineSymbol::EarthBankTagLine => 6.,
            LineSymbol::EarthWall => 21.,
            LineSymbol::RetainingEarthWall => 21.,
            LineSymbol::RuinedEarthWall => 55.,
            LineSymbol::ErosionGully => 17.25,
            LineSymbol::SmallErosionGully => 10.5,
            LineSymbol::ImpassableCliff => 9.,
            LineSymbol::ImpassableCliffTopLine => 9.,
            LineSymbol::ImpassableCliffTagLine => 6.,
            LineSymbol::Cliff => 9.,
            LineSymbol::CliffWithTags => 9.,
            LineSymbol::Trench => 15.,
            LineSymbol::CrossableWatercourse => 15.,
            LineSymbol::SmallCrossableWatercourse => 15.,
            LineSymbol::SeasonalWatercourse => 41.,
            LineSymbol::NarrowMarsh => 10.5,
            LineSymbol::Hedge => 17.,
            LineSymbol::DistinctCultivationBoundary => 30.,
            LineSymbol::DistinctVegetationBoundary => 27.,
            LineSymbol::VehicleTrack => 94.,
            LineSymbol::Footpath => 64.,
            LineSymbol::SmallFootpath => 34.,
            LineSymbol::IndistinctFootpath => 79.5,
            LineSymbol::NarrowRide => 48.,
            LineSymbol::NarrowRideEasyRunning => 48.,
            LineSymbol::NarrowRideNormalRunning => 48.,
            LineSymbol::NarrowRideSlowRunning => 48.,
            LineSymbol::NarrowRideWalk => 48.,
            LineSymbol::Railway => 60.,
            LineSymbol::ImpassableRailway => 60.,
            LineSymbol::SmallPowerLine => 75.,
            LineSymbol::LargePowerLine => 75.,
            LineSymbol::MajorPowerLine => 75.,
            LineSymbol::MajorPowerLineWithPylons => 75.,
            LineSymbol::BridgeTunnel => 6.,
            LineSymbol::Wall => 21.,
            LineSymbol::RetainingWall => 21.,
            LineSymbol::RuinedWall => 55.,
            LineSymbol::ImpassableWall => 45.,
            LineSymbol::Fence => 22.5,
            LineSymbol::RuinedFence => 55.,
            LineSymbol::ImpassableFence => 30.,
            LineSymbol::Ruin => 48.,
            LineSymbol::ProminentLinearFeature => 22.5,
            LineSymbol::ImpassableProminentLinearFeature => 30.,
            LineSymbol::Stairway => 24.,
            _ => 0.,
        };

        match scale {
            Scale::S10_000 => min * CONVERSION,
            Scale::S15_000 => min,
        }
    }

    fn id(&self) -> u8 {
        match self {
            LineSymbol::Contour => 0,
            LineSymbol::BasemapContour => 2,
            LineSymbol::NegBasemapContour => 3,
            LineSymbol::IndexContour => 4,
            LineSymbol::FormLine => 6,
            LineSymbol::EarthBank => 8,
            LineSymbol::EarthBankTopLine => 10,
            LineSymbol::EarthBankTagLine => 11,
            LineSymbol::EarthWall => 12,
            LineSymbol::RetainingEarthWall => 13,
            LineSymbol::RuinedEarthWall => 14,
            LineSymbol::ErosionGully => 15,
            LineSymbol::SmallErosionGully => 16,
            LineSymbol::ImpassableCliff => 25,
            LineSymbol::ImpassableCliffTopLine => 27,
            LineSymbol::ImpassableCliffTagLine => 28,
            LineSymbol::Cliff => 29,
            LineSymbol::CliffWithTags => 31,
            LineSymbol::Trench => 51,
            LineSymbol::BankLine => 56,
            LineSymbol::ShallowWaterOutline => 60,
            LineSymbol::ShallowWaterDashedOutline => 61,
            LineSymbol::CrossableWatercourse => 64,
            LineSymbol::SmallCrossableWatercourse => 65,
            LineSymbol::SeasonalWatercourse => 66,
            LineSymbol::NarrowMarsh => 71,
            LineSymbol::Hedge => 95,
            LineSymbol::DistinctCultivationBoundary => 101,
            LineSymbol::DistinctVegetationBoundary => 102,
            LineSymbol::PavedAreaBoundingLine => 109,
            LineSymbol::Road => 110,
            LineSymbol::RoadDualCarriageway => 111,
            LineSymbol::GravelRoad => 112,
            LineSymbol::VehicleTrack => 113,
            LineSymbol::Footpath => 114,
            LineSymbol::SmallFootpath => 115,
            LineSymbol::IndistinctFootpath => 116,
            LineSymbol::NarrowRide => 117,
            LineSymbol::NarrowRideEasyRunning => 118,
            LineSymbol::NarrowRideNormalRunning => 119,
            LineSymbol::NarrowRideSlowRunning => 120,
            LineSymbol::NarrowRideWalk => 121,
            LineSymbol::Railway => 122,
            LineSymbol::ImpassableRailway => 123,
            LineSymbol::SmallPowerLine => 124,
            LineSymbol::LargePowerLine => 125,
            LineSymbol::MajorPowerLine => 126,
            LineSymbol::MajorPowerLineWithPylons => 127,
            LineSymbol::BridgeTunnel => 128,
            LineSymbol::Wall => 131,
            LineSymbol::RetainingWall => 132,
            LineSymbol::RuinedWall => 133,
            LineSymbol::ImpassableWall => 134,
            LineSymbol::Fence => 135,
            LineSymbol::RuinedFence => 136,
            LineSymbol::ImpassableFence => 137,
            LineSymbol::PrivateAreaBoundingLine => 140,
            LineSymbol::LargeBuildingOutline => 145,
            LineSymbol::CanopyOutline => 148,
            LineSymbol::Ruin => 149,
            LineSymbol::ProminentLinearFeature => 155,
            LineSymbol::ImpassableProminentLinearFeature => 156,
            LineSymbol::Stairway => 159,
            LineSymbol::SimpleOrienteeringCourse => 166,
        }
    }
}
